/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hollydroppers;

import static hollydroppers.HollyDroppersFrame2.ptable;
import java.sql.ResultSet;

/**
 *
 * @author Arif
 */
public class addcgpa extends javax.swing.JFrame {
    
    String[]selectedtitle=new String[10];
    String []titlecgpa=new String[10];
    int addflag=0;
    int cgpacomboitem=1;
    int callsourceflag=0;
    
    /**
     * Creates new form addcgpa
     */

    public addcgpa(String[][] selectedtitle) {
        this.selectedtitle=new String [selectedtitle.length];
        this.titlecgpa=new String [selectedtitle.length];
        for(int i=0;i<selectedtitle.length;i++){
            this.selectedtitle[i]=selectedtitle[i][0];
            if(selectedtitle[i][1]=="0")
                callsourceflag=1;
            else
            this.titlecgpa[i]=selectedtitle[i][1];
        }
     
        initComponents();
    }
    public String[]getcgpacomboitem(){
       // String[]cgpacomboitem;
        if(callsourceflag==0){
            
            String cgpacomboitem[]={ "F", "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+" };
            return cgpacomboitem;
        }else{
            String cgpacomboitem[]={ "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+" };
            return cgpacomboitem;
        
            
        }
   }
    public void getselectedcgpaitem(){
        String title=(String)titlecombo.getSelectedItem();
        for(int i=0;i<selectedtitle.length;i++){
            if(title==selectedtitle[i]){
                System.out.println("value of selected item cgpa: "+titlecgpa[i]);
                if(titlecgpa[i].equals("Empty")){
                    cgpacombo.setSelectedItem("F");
                    
                    break;
                }else{
                    cgpacombo.setSelectedItem(titlecgpa[i]);
                    
                    break;
                }
            }
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlecombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cgpacombo = new javax.swing.JComboBox();
        addbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        addcounttextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlecombo.setModel(new javax.swing.DefaultComboBoxModel(selectedtitle));
        titlecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlecomboActionPerformed(evt);
            }
        });

        jLabel1.setText("  Title");

        jLabel2.setText(" CGPA");

        cgpacombo.setModel(new javax.swing.DefaultComboBoxModel(getcgpacomboitem()));
        if(callsourceflag==0){
            getselectedcgpaitem();
        }
        cgpacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpacomboActionPerformed(evt);
            }
        });

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        addcounttextfield.setEditable(false);
        addcounttextfield.setText(null);
        addcounttextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcounttextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cgpacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addcounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cgpacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(addcounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(cancelbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cgpacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpacomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpacomboActionPerformed

    private void addcounttextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcounttextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcounttextfieldActionPerformed
    
    public void exit(){
        dispose();
    }
    
    
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String combotitle=(String)titlecombo.getSelectedItem();
        String cgpa=(String)cgpacombo.getSelectedItem();
        boolean error=false;
        boolean searchresult=false;
        String msg="";
        connectDB cdb=new connectDB();
        
        cgpacomboitem=cgpacomboitem+ cgpacombo.getSelectedIndex();
        searchresult= cdb.search("select* from dropped_course where title='"+combotitle+"';");
       // HollyDroppersFrame2 hd=new HollyDroppersFrame2();
        if(combotitle!=null){
            if(cgpacomboitem==1){
            if(!searchresult){
              //cdb.getResultset()=cdb.getStatement().executeQuery();
                
                String sql="delete from passed_course where title='"+combotitle+"';" ;
                error=cdb.deleterow(sql);
                if(error){
                   addflag++;
                   msg="       Added To Dropped Course : "+addflag;   
             }else
                 msg="       Already Added in Dropped Course.";
            
            }else
                msg="       Already Added in Dropped Course.";
            
           
        }else{//cgpa)values('"+cgpacombo.getSelectedItem()+"')
             String sql="update passed_course set cgpa='"+cgpacombo.getSelectedItem()+"' where title='"+combotitle+"';" ;
            //String sql="insert into passed_course(`serial`,`year`,`semester`,`code`,`title`,`credit`,`cgpa`) Select s.*,'"+cgpa+"' From subjecttable s where title='"+combotitle+"';" ;
            error= cdb.insertdata(sql);
             if(error){
                 addflag++;
                 msg="        pAdded Now : "+addflag;

             }else
                 msg="        pAlready Added .";
             
             
        }
        }

        else
            msg="            Select subject first .";
        
       addcounttextfield.setText(msg);
    }//GEN-LAST:event_addbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void titlecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlecomboActionPerformed
        // TODO add your handling code here:
        if(callsourceflag==0)
        getselectedcgpaitem();
    }//GEN-LAST:event_titlecomboActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField addcounttextfield;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox cgpacombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox titlecombo;
    // End of variables declaration//GEN-END:variables
}
