 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hollydroppers;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Arif
 */
public class AddNewFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddNewFrame
     */
    int yearcomboitem=1;int semcomboitem=1;
    int cgpacomboitem=1;
    int addflag=0;
    String combotitle;
    ComboBoxModel model;
    public AddNewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yearcombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        semcombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cgpacombo = new javax.swing.JComboBox();
        addbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        titlecombo = new javax.swing.JComboBox();
        addcounttextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("   Year");

        yearcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        yearcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearcomboActionPerformed(evt);
            }
        });

        jLabel2.setText("  Sem");

        semcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        semcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semcomboActionPerformed(evt);
            }
        });

        jLabel3.setText("   Title  ");

        jLabel4.setText("   CGPA");

        cgpacombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F","Empty", "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+" }));
        cgpacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpacomboActionPerformed(evt);
            }
        });

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Back");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        connectDB cdb=new connectDB();
        String sql="Select title From subjecttable Where year='1' and semester='1';";
        titlecombo.setModel(new javax.swing.DefaultComboBoxModel(cdb.titlecomboitem(sql)));
        titlecombo.setMaximumSize(new java.awt.Dimension(28, 20));
        titlecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlecomboActionPerformed(evt);
            }
        });

        addcounttextfield.setEditable(false);
        addcounttextfield.setText("    Added Now :  0");
        addcounttextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcounttextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cgpacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(semcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(addbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelbutton)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addcounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(semcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(titlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cgpacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(addcounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(cancelbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearcomboActionPerformed
        // TODO add your handling code here:
        yearcomboitem=1+(int)yearcombo.getSelectedIndex();
        connectDB cdb=new connectDB();
        String sql="Select title From subjecttable Where year='"+yearcomboitem+"' and semester='"+semcomboitem+"';";
        model=new DefaultComboBoxModel(cdb.titlecomboitem(sql));
        titlecombo.setModel(model);
    }//GEN-LAST:event_yearcomboActionPerformed

    private void semcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semcomboActionPerformed
        // TODO add your handling code here:
        semcomboitem=1+semcombo.getSelectedIndex();
        connectDB cdb=new connectDB();
        String sql="Select title From subjecttable Where year='"+yearcomboitem+"' and semester='"+semcomboitem+"';";
        model=new DefaultComboBoxModel(cdb.titlecomboitem(sql));
        titlecombo.setModel(model);
    }//GEN-LAST:event_semcomboActionPerformed

    private void titlecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlecomboActionPerformed
        // TODO add your handling code here:
     
        System.out.println(combotitle);
    }//GEN-LAST:event_titlecomboActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        
        
        exit();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        combotitle=(String)titlecombo.getSelectedItem();
        String cgpa=(String)cgpacombo.getSelectedItem();
        boolean error=false;
        String msg="";
        connectDB cdb=new connectDB();
       // HollyDroppersFrame2 hd=new HollyDroppersFrame2();
        
        if(cgpacomboitem==1){
            boolean searchsql=cdb.search("select* from passed_course where title='"+combotitle+"';");
            if(!searchsql){
                String sql="insert into dropped_course Select* From subjecttable where title='"+combotitle+"';" ;
                error= cdb.insertdata(sql);
                if(error){
                    addflag++;
                     msg="       Added Now : "+addflag;   
                }else
                     msg="       Already Added .";
                }else
                    msg="Delete From Passed Course first.";

            
           
        }else{
             String sql="delete from dropped_course where title='"+combotitle+"';" ;
             boolean hudai=cdb.deleterow(sql);
             sql="insert into passed_course Select s.*,'"+cgpa+"' From subjecttable s where"
                     + " title='"+combotitle+"';" ;
            //String sql="insert into passed_course(`serial`,`year`,`semester`,`code`,`title`,`credit`,`cgpa`) Select s.*,'"+cgpa+"' From subjecttable s where title='"+combotitle+"';" ;
            error= cdb.insertdata(sql);
             if(error){
                 addflag++;
                 msg="        pAdded Now : "+addflag;

             }else
                 msg="        pAlready Added .";
             
             
        }
        
       addcounttextfield.setText(msg);
    }//GEN-LAST:event_addbuttonActionPerformed

    private void cgpacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpacomboActionPerformed
        // TODO add your handling code here:
        cgpacomboitem=1+cgpacombo.getSelectedIndex();
    }//GEN-LAST:event_cgpacomboActionPerformed

    private void addcounttextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcounttextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcounttextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void exit(){
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField addcounttextfield;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JComboBox cgpacombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox semcombo;
    private javax.swing.JComboBox titlecombo;
    private javax.swing.JComboBox yearcombo;
    // End of variables declaration//GEN-END:variables
}
