/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hollydroppers;

import java.awt.GraphicsConfiguration;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultCellEditor;
import javafx.scene.control.TitledPane;
import javafx.scene.control.Accordion;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Arifur Rahman
 */
public class HollyDroppersFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form HollyDroppersFrame2
     */
    Ptablemodel ptm=new Ptablemodel();
   int []checkarray=new int[15];

    HollyDroppersFrame2(int i) {
       
    }
    
    public HollyDroppersFrame2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pyearcombobox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        psemcombobox = new javax.swing.JComboBox();
        paddnewbutton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        ptotalcredittextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cgpatextfield = new javax.swing.JTextField();
        premove = new javax.swing.JButton();
        addcgpabtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dyearcombobox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        dsemcombobox = new javax.swing.JComboBox();
        daddnewbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtable = new javax.swing.JTable();
        dpassed = new javax.swing.JButton();
        dremove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dtotalcredittextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(51, 102, 255));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("CSE Depatment : 3rd year 1st semester");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setText("!");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(88, 88, 88))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 397, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Current Course", jPanel4);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("    Year");

        pyearcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2", "3", "4" }));
        pyearcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyearcomboboxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("  Sem");

        psemcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2" }));
        psemcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psemcomboboxActionPerformed(evt);
            }
        });

        paddnewbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paddnewbutton.setText("Add New");
        paddnewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paddnewbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psemcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(paddnewbutton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(psemcombobox)
            .addComponent(paddnewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ptable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(ptable);

        ptotalcredittextfield.setEditable(false);
        ptotalcredittextfield.setText(null);

        jLabel6.setText("Total Credits :-:");

        jLabel7.setText(" CGPA:-:");

        cgpatextfield.setEditable(false);
        cgpatextfield.setText("0.00");
        cgpatextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpatextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cgpatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ptotalcredittextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(ptotalcredittextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cgpatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        premove.setText("Remove");
        premove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premoveActionPerformed(evt);
            }
        });

        addcgpabtn.setText("Add CGPA");
        addcgpabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcgpabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(addcgpabtn)
                        .addGap(5, 5, 5)
                        .addComponent(premove)
                        .addGap(42, 42, 42))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addcgpabtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Passed Course", jPanel5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("    Year");

        dyearcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2", "3", "4" }));
        dyearcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyearcomboboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("  Sem");

        dsemcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2" }));
        dsemcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsemcomboboxActionPerformed(evt);
            }
        });

        daddnewbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        daddnewbutton.setText("Add New");
        daddnewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daddnewbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dsemcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(daddnewbutton)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(daddnewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dsemcombobox)
        );

        dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "y/s", "code", "title", "credit", "select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dtable.setRowHeight(18);
        jScrollPane1.setViewportView(dtable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dpassed.setText("Passed");
        dpassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpassedActionPerformed(evt);
            }
        });

        dremove.setText("Remove");
        dremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dremoveActionPerformed(evt);
            }
        });

        jLabel5.setText("  Total Credits :-:");

        dtotalcredittextfield.setEditable(false);
        dtotalcredittextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtotalcredittextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(dpassed)
                        .addGap(18, 18, 18)
                        .addComponent(dremove))
                    .addComponent(dtotalcredittextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtotalcredittextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpassed)
                    .addComponent(dremove))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Dropped Course", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDremove(JButton dremove) {
        this.dremove = dremove;
    }
    public String psqlgenerator(){
               
        String yearcomboitem= (String)pyearcombobox.getSelectedItem();
        String semcomboitem= (String)psemcombobox.getSelectedItem();
                System.out.println("hello honye "+semcomboitem);
         String sql;
        if(yearcomboitem=="All" &semcomboitem!="All"){
            sql="Select* From passed_course Where semester='"+semcomboitem+"';";
        }
        else if(semcomboitem=="All"&yearcomboitem!="All"){
            sql="Select* From passed_course Where year='"+yearcomboitem+"';";
        }
        else if(yearcomboitem=="All" &semcomboitem=="All"){
            sql="Select* From passed_course;";
        }else
        sql="Select* From passed_course Where year='"+yearcomboitem+"'and semester='"+semcomboitem+"';";
       return sql;
    }
    private String dsqlgenerator(){
        
       
        String yearcomboitem= (String)dyearcombobox.getSelectedItem();
        String semcomboitem= (String)dsemcombobox.getSelectedItem();
         String sql;
        if(yearcomboitem=="All" &semcomboitem!="All"){
            sql="Select* From dropped_course Where semester='"+semcomboitem+"';";
        }
        else if(semcomboitem=="All"&yearcomboitem!="All"){
            sql="Select* From dropped_course Where year='"+yearcomboitem+"';";
        }
        else if(yearcomboitem=="All" &semcomboitem=="All"){
            sql="Select* From dropped_course;";
        }else
        sql="Select* From dropped_course Where year='"+yearcomboitem+"'and semester='"+semcomboitem+"';";
       return sql;

    }
    private void dyearcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyearcomboboxActionPerformed
        // TODO add your handling code here:
        dtable.setModel(new Dtablemodel(dsqlgenerator()));
        dtotalcredittextfield.setText(""+new Dtablemodel().gettotal());

    }//GEN-LAST:event_dyearcomboboxActionPerformed

    private void pyearcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyearcomboboxActionPerformed
        // TODO add your handling code here:
        ptable.setModel(new Ptablemodel(psqlgenerator()));
        cgpatextfield.setText(""+new Ptablemodel().getcgpa());
        ptotalcredittextfield.setText(""+new Ptablemodel().gettotal());
        
    }//GEN-LAST:event_pyearcomboboxActionPerformed

    private void dsemcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsemcomboboxActionPerformed
        // TODO add your handling code here:

        dtable.setModel(new Dtablemodel(dsqlgenerator()));
        dtotalcredittextfield.setText(""+new Dtablemodel().gettotal());
       System.out.println("height of table:"+dtable.getRowHeight()*dtable.getRowCount());
        System.out.println("height of t   able:"+dtable.getHeight());
    }//GEN-LAST:event_dsemcomboboxActionPerformed

    private void dpassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpassedActionPerformed
        // TODO add your handling code here:
         int size=0;
         Dtablemodel dtm=new Dtablemodel();
        
         
          for(int i=0;i<dtm.checkarray.length;i++){
              if(dtm.checkarray[i]==1){
                  size++;
              }

              
          }
          if(size==0){
              JOptionPane.showMessageDialog(null, "Select First!");
          }else{
            String[][] selectedtitle=new String[size][2];
            int j=0;
            for(int i=0;i<dtm.checkarray.length;i++){
              if(dtm.checkarray[i]==1){
                  selectedtitle[j][0]=(String)dtable.getValueAt(i,2 );
                  //selectedtitle[j][1]=(String)dtable.getValueAt(i,3 );
                  selectedtitle[j][1]="0";
                  //System.out.println("title selected:"+ selectedtitle[j]);
                  j++;
              }
              
              
          }
            addcgpa cgpa=new addcgpa(selectedtitle);
            cgpa.setVisible(true);
            cgpa.setResizable(false);
            cgpa.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          }
     

        
    }//GEN-LAST:event_dpassedActionPerformed

    private void daddnewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daddnewbuttonActionPerformed
        // TODO add your handling code here:
        AddNewFrame addnewFrame=new AddNewFrame();
        addnewFrame.setVisible(true);
        addnewFrame.setResizable(false);
        addnewFrame.setLocation(850,50);

        addnewFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dtable.setModel(new Dtablemodel(dsqlgenerator()));
        System.out.println("hello kemon acho tumi ?????????");
        //try{wait(DISPOSE_ON_CLOSE);}catch(Exception e){}
        
    }//GEN-LAST:event_daddnewbuttonActionPerformed

    private void paddnewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paddnewbuttonActionPerformed
        // TODO add your handling code here:
        AddNewFrame addnewFrame=new AddNewFrame();
        addnewFrame.setVisible(true);
        addnewFrame.setResizable(false);
        addnewFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_paddnewbuttonActionPerformed

    private void psemcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psemcomboboxActionPerformed
        // TODO add your handling code here:
        ptable.setModel(new Ptablemodel(psqlgenerator()));
        ptotalcredittextfield.setText(""+new Ptablemodel().gettotal());
        cgpatextfield.setText(""+new Ptablemodel().getcgpa());
    }//GEN-LAST:event_psemcomboboxActionPerformed

    private void dremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dremoveActionPerformed
        // TODO add your handling code here:

       

           Dtablemodel dtm=new Dtablemodel();
           connectDB db=new connectDB();
           String sql=""; 
           
           boolean deleteflag=false;
         
          for(int i=0;i<dtm.checkarray.length;i++){
              if(dtm.checkarray[i]==1){
                  sql="delete from dropped_course where code='"+dtable.getValueAt(i, 1)+"';";
                  System.out.println("value of row:"+dtable.getValueAt(i, 1));
                  db.deleterow(sql);
                  deleteflag=true;
                
              }

              
          }
         
              
       dtable.setModel(new Dtablemodel(dsqlgenerator()));
       dtotalcredittextfield.setText(""+new Dtablemodel().gettotal());
          if(deleteflag){
              deleteflag=false;
              JOptionPane.showMessageDialog(null, "Removed.");
          }else
              JOptionPane.showMessageDialog(null, "Select First !");
          


          
          
    }//GEN-LAST:event_dremoveActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
        ptable.setModel(new Ptablemodel(psqlgenerator()));
        ptotalcredittextfield.setText(""+new Ptablemodel().gettotal());
        cgpatextfield.setText(""+new Ptablemodel().getcgpa());
        dtable.setModel(new Dtablemodel(dsqlgenerator()));
        dtotalcredittextfield.setText(""+new Dtablemodel().gettotal());
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void dtotalcredittextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtotalcredittextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtotalcredittextfieldActionPerformed

    private void premoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premoveActionPerformed
        // TODO add your handling code here:
        
            
           connectDB db=new connectDB();
           String sql=""; 
           boolean deleteflag=false;
          for(int i=0;i<ptm.checkarray.length;i++){
              if(ptm.checkarray[i]==1){
                  sql="delete from passed_course where code='"+ptable.getValueAt(i, 1)+"';";
                  System.out.println("value of row:"+ptable.getValueAt(i, 1));
                  db.deleterow(sql);
                  deleteflag=true;
              }

              
          }
     

          
      
       ptable.setModel(new Ptablemodel(psqlgenerator()));
       ptotalcredittextfield.setText(""+new Ptablemodel().gettotal());
       cgpatextfield.setText(""+new Ptablemodel().getcgpa());
       
       if(deleteflag){
           deleteflag=false;
           JOptionPane.showMessageDialog(null,"Removed.");
       }else 
           JOptionPane.showMessageDialog(null, "Select First!");
        
    }//GEN-LAST:event_premoveActionPerformed

    private void addcgpabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcgpabtnActionPerformed

        int size=0;
       
        
         
          for(int i=0;i<ptm.checkarray.length;i++){
              if(ptm.checkarray[i]==1){
                  size++;
              }

              
          }
          if(size==0){
              JOptionPane.showMessageDialog(null, "Select First!");
          }else{
            String[][] selectedtitle=new String[size][2];
            int j=0;
            for(int i=0;i<ptm.checkarray.length;i++){
              if(ptm.checkarray[i]==1){
                  selectedtitle[j][0]=(String)ptable.getValueAt(i,2 );
                  selectedtitle[j][1]=(String)ptable.getValueAt(i,4 );
                  //System.out.println("title selected:"+ selectedtitle[j]);
                  j++;
              }
              
              
          }
            addcgpa cgpa=new addcgpa(selectedtitle);
            cgpa.setVisible(true);
            cgpa.setResizable(false);
            cgpa.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          }
     


       

        
          
    }//GEN-LAST:event_addcgpabtnActionPerformed

    private void cgpatextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpatextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpatextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HollyDroppersFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HollyDroppersFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HollyDroppersFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HollyDroppersFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               HollyDroppersFrame2 ja= new HollyDroppersFrame2();
                ja.setVisible(true);
                ja.setLocation(250, 20);
                ja.setDefaultCloseOperation(EXIT_ON_CLOSE);
               
                
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcgpabtn;
    private javax.swing.JTextField cgpatextfield;
    private javax.swing.JButton daddnewbutton;
    private javax.swing.JButton dpassed;
    private javax.swing.JButton dremove;
    private javax.swing.JComboBox dsemcombobox;
    private javax.swing.JTable dtable;
    private javax.swing.JTextField dtotalcredittextfield;
    private javax.swing.JComboBox dyearcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton paddnewbutton;
    private javax.swing.JButton premove;
    private javax.swing.JComboBox psemcombobox;
    static javax.swing.JTable ptable;
    javax.swing.JTextField ptotalcredittextfield;
    private javax.swing.JComboBox pyearcombobox;
    // End of variables declaration//GEN-END:variables
}
